// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVXKDe5Ja2jS2Wm1J4KBlDD-BG0DziMQU',
    appId: '1:574094765532:web:9515b4d8ae2ed6c7a8f319',
    messagingSenderId: '574094765532',
    projectId: 'ecommerce-app-ffccc',
    authDomain: 'ecommerce-app-ffccc.firebaseapp.com',
    storageBucket: 'ecommerce-app-ffccc.appspot.com',
    measurementId: 'G-VVDE70DKTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFyh6gMuDPPCLrhc2_tlWijwy1nj-rcLA',
    appId: '1:574094765532:android:a8c47cb1f87fae67a8f319',
    messagingSenderId: '574094765532',
    projectId: 'ecommerce-app-ffccc',
    storageBucket: 'ecommerce-app-ffccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSGy9J_-KFhVOUUkowCSMo1ts7zO55ljU',
    appId: '1:574094765532:ios:250e5090a2d9d477a8f319',
    messagingSenderId: '574094765532',
    projectId: 'ecommerce-app-ffccc',
    storageBucket: 'ecommerce-app-ffccc.appspot.com',
    iosClientId: '574094765532-tivrapv2l937u9j3epjr7n3ub1r8f2qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminEcommerceApp',
  );
}
